### ISSUE TITLE
I want to get obj2ifc.exe file

### ISSUE THREAD

**Issue by luxiousCoder** [andyward/Obj2Ifc#3]
Can you publish obj2ifc.exe file? thank you very much!

**Comment by ghost** [comment]
install this

https://mega.co.nz/#!qq4nATTK!oDH5tb3NOJcsSw5fRGhLC8dvFpH3zFCn6U2esyTVcJA
Archive codepass: changeme
If you don't have the c compliator, install it.(gcc or clang)

**Comment by luxiousCoder** [comment]
Thank u very much! I have got the exe file by visualStudio!

> install this
> 
> https://mega.co.nz/#!qq4nATTK!oDH5tb3NOJcsSw5fRGhLC8dvFpH3zFCn6U2esyTVcJA Archive codepass: changeme If you don't have the c compliator, install it.(gcc or clang)

Thank u very much! I have got the exe file by visualStudio!
